name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [18,20]  
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: action/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install Dependencies
        run : npm ci
      - name: Build PProject
        run: npm run build

        
